### PR TITLE
Remove Bo from Pets of Netlify

### PR DESCRIPTION
**Pull request by emilieschario**

### CODE REVIEW

**Comment by philhawksworth** [comment]
👷 Deploy Matey is creating a build preview.


🔨 Explore the source changes: 7dde75351bcd905cb542efa0a960f48d636cdf1a

🔍 Inspect the deploy log: [https://app.netlify.com/sites/petsof/deploys/619558490717a00008cd0538](https://app.netlify.com/sites/petsof/deploys/619558490717a00008cd0538)

**Comment by emilieschario** [comment]
@rybit wanna merge this for me?

**Comment by emilieschario** [comment]
👋 @brienna !!!

**Comment by rybit** [comment]
@emilieschario, looks like you're the one that managed to figure out that this build has been broken forever. I'll find an owner for that fix.

**Comment by verythorough** [comment]
Looks like there are two sites connected to this repo, and the one that matters (the one that deploys to petsofnetlify.com) is building just fine. 

I'm going to go ahead and merge, but maybe @rafaelconde (Hi! 👋🏻) would you like to remove the [test site](https://app.netlify.com/sites/clever-ardinghelli-cba588/deploys/61955849826b28000854d5ed) you have connected here? (Or turn off deploy notifications, or upgrade the build image so builds succeed)

**Comment by rafaelconde** [comment]
Done ✔️ 

Hi @verythorough 👋 ❤️

**Pull request merged**
