### PR TITLE
Add hash links for each pet

### PR DESCRIPTION
**Pull request by rocktronica**
And give em the ol razzle dazzle!

Screen Shot 2020-06-10 at 6 53 34 PM

---

This change will allow humans to send other humans nice links to their respective animals :)

### CODE REVIEW

**Comment by philhawksworth** [comment]
Deploy Matey is creating a build preview.

Building with commit 812880234083330c1a372d80e9a864e45e66d80b

https://app.netlify.com/sites/petsof/deploys/5ee1b1922d455c00081af2f9

**Comment by rocktronica** [comment]
I don't think I can add a label to appease the @tools-netlify check, so I'll hand this over to anybody who'd like it? Or LMK what I can do for it.

(Baño is my cat! <3)

**Comment by rafaelconde** [comment]
@philhawksworth can you add labels? We need to fix this 😅

**Comment by leiarollag** [comment]
Fun!  Yay!

**Pull request merged**
